### PR TITLE
SNP Simulation Method

### PR DESCRIPTION
**Pull request by BrendonChau**
Implemented fast sampling for SNPs directly in the compressed format used by SnpArrays. This uses minimum allocations and should be useful for downstream simulations. Sampling is pretty fast, on my machine, it only takes around 90 seconds to simulate 100k SNPs from 500k subjects. Multithreading should be possible, but it's already fast enough for most use cases.

### CODE REVIEW

**Comment by kose-y** [comment]
Thanks, looks nice! Could you please add some unit tests?

**Comment by BrendonChau** [comment]
I've implemented a method for simulating missing SNP data as well and put in some basic unit tests for checking that the proportions are correct.

**Comment by kose-y** [comment]
Oh, one more thing. Could you please add the docs about the new functions? The sources are in Jupyter Notebooks in the docs directory.

**Comment by BrendonChau** [comment]
I've implemented a way to simulate SNPs under assuming a AR1 LD structure with constant `ρ`, to my knowledge, there is no scalable method for doing this for tens of thousands of SNPs. On my machine, simulating `100_000` SNPs from `500_000` subjects only takes a little over 4 minutes and can be done entirely in-memory. Being able to simulate SNPs with linkage disequilibrium is important for downstream methods development.

I also updated the docs to include examples, but there is some problems with the sections related to ADMIXTURE, could someone take a look?

**Review by kose-y — APPROVED** [review]
Looks good to me. Thanks for your contribution.

**Pull request merged**
